### ISSUE TITLE
install failed at the end of bootstrap.bat

### ISSUE THREAD

**Issue by jahnc** [LuaDist/Repository#219]
it runs all the way (taking a long while) as expected until -
## Boostrap done, building LuaDist using LuaDist
'C:\Program' is not recognized as an internal or external command, ...

that is, it fails on -
%LUADIST% "%INSTALL%" install luadist-git -binary=false -source %*

**Comment by drahosp** [comment]
Seems to me like you are trying to bootstrap in a working directory with a space in the path. Please try running it from a working directory without spaces eg. C:/Work/. Additional information would be helpful, for example pasting the build log and system details.
