### ISSUE TITLE
"bootstrap.bat command not found"

### ISSUE THREAD

**Issue by xuurcanx** [LuaDist/Repository#228]
I'm failing on getting lua on both windows and linux due to my limited knowledge over and over again. on mingw64 I'm getting this error saying "bootstrap.bat command not found" after inputting "bootstrap.bat". c, c++ compiler, cmake and git is already installed btw.

**Comment by JaneShenYY** [comment]
Try run this script in your Git Bash:
cmd "/C  bootstrap.bat"
